
---
- hosts: all

  tasks:
  - name: install example application
    copy:
      src: ansible-pull-test
      dest: /tmp/
      owner: root
      group: root

  - name: copy deb packages
    become: yes
    action: copy
    args:
      src: /ansible-pull-test/{{item}}
      dest: /tmp/{{item}}
      mode: 0644
      backup: no
      with_items:
       - my-apptest.1.0.0.ubuntu.18.04-x64.deb

  - name: install Deb
    become: yes 
    apt: deb=/tmp/{{item}} 
    with_items:
      - my-apptest.1.0.0.ubuntu.18.04-x64.deb


