
---
- hosts: localhost

  tasks:
  - name: install example application
    copy:
      src: ansible-pull-test
      dest: /tmp/
      owner: root
      group: root
  
  - name: install Deb
    become: yes 
    apt: 
      deb: https://github.com/nikhilsivadas-Developer/AnsiblePull/blob/6e0fa5e87105c7a74b4664c0e6b355c3373216f2/installapp.yml

#  - name: install Deb
#    become: yes 
#    apt: deb=/tmp/ansible-pull-test/{{item}}  
#    with_items:
#      - my-apptest.1.0.0.ubuntu.18.04-x64.deb


